from pyglet.gl import (
    GL_FLOAT, GL_FLOAT_VEC2, GL_FLOAT_VEC3, GL_FLOAT_VEC4, GL_DOUBLE, GL_DOUBLE_VEC2, GL_DOUBLE_VEC3, GL_DOUBLE_VEC4,
    GL_INT, GL_INT_VEC2, GL_INT_VEC3, GL_INT_VEC4, GL_UNSIGNED_INT, GL_UNSIGNED_INT_VEC2, GL_UNSIGNED_INT_VEC3,
    GL_UNSIGNED_INT_VEC4, GL_BOOL, GL_BOOL_VEC2, GL_BOOL_VEC3, GL_BOOL_VEC4, GL_FLOAT_MAT2, GL_FLOAT_MAT3,
    GL_FLOAT_MAT4, GL_FLOAT_MAT2x3, GL_FLOAT_MAT2x4, GL_FLOAT_MAT3x2, GL_FLOAT_MAT3x4, GL_FLOAT_MAT4x2,
    GL_FLOAT_MAT4x3, GL_DOUBLE_MAT2, GL_DOUBLE_MAT3, GL_DOUBLE_MAT4, GL_DOUBLE_MAT2x3, GL_DOUBLE_MAT2x4,
    GL_DOUBLE_MAT3x2, GL_DOUBLE_MAT3x4, GL_DOUBLE_MAT4x2, GL_DOUBLE_MAT4x3, GL_SAMPLER_1D, GL_SAMPLER_2D,
    GL_SAMPLER_3D, GL_SAMPLER_CUBE, GL_SAMPLER_1D_SHADOW, GL_SAMPLER_2D_SHADOW, GL_SAMPLER_1D_ARRAY,
    GL_SAMPLER_2D_ARRAY, GL_SAMPLER_1D_ARRAY_SHADOW, GL_SAMPLER_2D_ARRAY_SHADOW, GL_SAMPLER_2D_MULTISAMPLE,
    GL_SAMPLER_2D_MULTISAMPLE_ARRAY, GL_SAMPLER_CUBE_SHADOW, GL_SAMPLER_BUFFER, GL_SAMPLER_2D_RECT,
    GL_SAMPLER_2D_RECT_SHADOW, GL_INT_SAMPLER_1D, GL_INT_SAMPLER_2D, GL_INT_SAMPLER_3D, GL_INT_SAMPLER_CUBE,
    GL_INT_SAMPLER_1D_ARRAY, GL_INT_SAMPLER_2D_ARRAY, GL_INT_SAMPLER_2D_MULTISAMPLE,
    GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, GL_INT_SAMPLER_BUFFER, GL_INT_SAMPLER_2D_RECT, GL_UNSIGNED_INT_SAMPLER_1D,
    GL_UNSIGNED_INT_SAMPLER_2D, GL_UNSIGNED_INT_SAMPLER_3D, GL_UNSIGNED_INT_SAMPLER_CUBE,
    GL_UNSIGNED_INT_SAMPLER_1D_ARRAY, GL_UNSIGNED_INT_SAMPLER_2D_ARRAY, GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE,
    GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, GL_UNSIGNED_INT_SAMPLER_BUFFER, GL_UNSIGNED_INT_SAMPLER_2D_RECT,
    GL_IMAGE_1D, GL_IMAGE_2D, GL_IMAGE_3D, GL_IMAGE_2D_RECT, GL_IMAGE_CUBE, GL_IMAGE_BUFFER, GL_IMAGE_1D_ARRAY,
    GL_IMAGE_2D_ARRAY, GL_IMAGE_2D_MULTISAMPLE, GL_IMAGE_2D_MULTISAMPLE_ARRAY, GL_INT_IMAGE_1D, GL_INT_IMAGE_2D,
    GL_INT_IMAGE_3D, GL_INT_IMAGE_2D_RECT, GL_INT_IMAGE_CUBE, GL_INT_IMAGE_BUFFER, GL_INT_IMAGE_1D_ARRAY,
    GL_INT_IMAGE_2D_ARRAY, GL_INT_IMAGE_2D_MULTISAMPLE, GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY, GL_UNSIGNED_INT_IMAGE_1D,
    GL_UNSIGNED_INT_IMAGE_2D, GL_UNSIGNED_INT_IMAGE_3D, GL_UNSIGNED_INT_IMAGE_2D_RECT, GL_UNSIGNED_INT_IMAGE_CUBE,
    GL_UNSIGNED_INT_IMAGE_BUFFER, GL_UNSIGNED_INT_IMAGE_1D_ARRAY, GL_UNSIGNED_INT_IMAGE_2D_ARRAY,
    GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE, GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY, GL_UNSIGNED_INT_ATOMIC_COUNTER,

    glUniform1f, glUniform2f, glUniform3f, glUniform4f, glUniform1d, glUniform2d, glUniform3d, glUniform4d, glUniform1i,
    glUniform2i, glUniform3i, glUniform4i, glUniform1ui, glUniform2ui, glUniform3ui, glUniform4ui, glUniformMatrix2fv,
    glUniformMatrix3fv, glUniformMatrix4fv, glUniformMatrix2x3fv, glUniformMatrix2x4fv, glUniformMatrix3x2fv,
    glUniformMatrix3x4fv, glUniformMatrix4x2fv, glUniformMatrix4x3fv, glUniformMatrix2dv, glUniformMatrix3dv,
    glUniformMatrix4dv, glUniformMatrix2x3dv, glUniformMatrix2x4dv, glUniformMatrix3x2dv, glUniformMatrix3x4dv,
    glUniformMatrix4x2dv, glUniformMatrix4x3dv,

    GLfloat, GLdouble, GLuint, GLint, GLboolean
)

table = {
	'float'               : {'shape': (1, )  , 'function': glUniform1f         , 'constant': GL_FLOAT,                  'dtype': GLfloat},
	'vec2'                : {'shape': (2, )  , 'function': glUniform2f         , 'constant': GL_FLOAT_VEC2,             'dtype': GLfloat},
	'vec3'                : {'shape': (3, )  , 'function': glUniform3f         , 'constant': GL_FLOAT_VEC3,             'dtype': GLfloat},
	'vec4'                : {'shape': (4, )  , 'function': glUniform4f         , 'constant': GL_FLOAT_VEC4,             'dtype': GLfloat},
	'double'              : {'shape': (1, )  , 'function': glUniform1d         , 'constant': GL_DOUBLE,                 'dtype': GLdouble},
	'dvec2'               : {'shape': (2, )  , 'function': glUniform2d         , 'constant': GL_DOUBLE_VEC2,            'dtype': GLdouble},
	'dvec3'               : {'shape': (3, )  , 'function': glUniform3d         , 'constant': GL_DOUBLE_VEC3,            'dtype': GLdouble},
	'dvec4'               : {'shape': (4, )  , 'function': glUniform4d         , 'constant': GL_DOUBLE_VEC4,            'dtype': GLdouble},
	'int'                 : {'shape': (1, )  , 'function': glUniform1i         , 'constant': GL_INT,                    'dtype': GLint},
	'ivec2'               : {'shape': (2, )  , 'function': glUniform2i         , 'constant': GL_INT_VEC2,               'dtype': GLint},
	'ivec3'               : {'shape': (3, )  , 'function': glUniform3i         , 'constant': GL_INT_VEC3,               'dtype': GLint},
	'ivec4'               : {'shape': (4, )  , 'function': glUniform4i         , 'constant': GL_INT_VEC4,               'dtype': GLint},
	'unsigned int'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT,           'dtype': GLuint},
	'uvec2'               : {'shape': (2, )  , 'function': glUniform2ui        , 'constant': GL_UNSIGNED_INT_VEC2,      'dtype': GLuint},
	'uvec3'               : {'shape': (3, )  , 'function': glUniform3ui        , 'constant': GL_UNSIGNED_INT_VEC3,      'dtype': GLuint},
	'uvec4'               : {'shape': (4, )  , 'function': glUniform4ui        , 'constant': GL_UNSIGNED_INT_VEC4,      'dtype': GLuint},
	'bool'                : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_BOOL,                   'dtype': GLuint},
	'bvec2'               : {'shape': (2, )  , 'function': glUniform2ui        , 'constant': GL_BOOL_VEC2,              'dtype': GLuint},
	'bvec3'               : {'shape': (3, )  , 'function': glUniform3ui        , 'constant': GL_BOOL_VEC3,              'dtype': GLuint},
	'bvec4'               : {'shape': (4, )  , 'function': glUniform4ui        , 'constant': GL_BOOL_VEC4,              'dtype': GLuint},
	'mat2'                : {'shape': (2, 2) , 'function': glUniformMatrix2fv  , 'constant': GL_FLOAT_MAT2,             'dtype': GLfloat},
	'mat3'                : {'shape': (3, 3) , 'function': glUniformMatrix3fv  , 'constant': GL_FLOAT_MAT3,             'dtype': GLfloat},
	'mat4'                : {'shape': (4, 4) , 'function': glUniformMatrix4fv  , 'constant': GL_FLOAT_MAT4,             'dtype': GLfloat},
	'mat2x3'              : {'shape': (2, 3) , 'function': glUniformMatrix2x3fv, 'constant': GL_FLOAT_MAT2x3,           'dtype': GLfloat},
	'mat2x4'              : {'shape': (2, 4) , 'function': glUniformMatrix2x4fv, 'constant': GL_FLOAT_MAT2x4,           'dtype': GLfloat},
	'mat3x2'              : {'shape': (3, 2) , 'function': glUniformMatrix3x2fv, 'constant': GL_FLOAT_MAT3x2,           'dtype': GLfloat},
	'mat3x4'              : {'shape': (3, 4) , 'function': glUniformMatrix3x4fv, 'constant': GL_FLOAT_MAT3x4,           'dtype': GLfloat},
	'mat4x2'              : {'shape': (4, 2) , 'function': glUniformMatrix4x2fv, 'constant': GL_FLOAT_MAT4x2,           'dtype': GLfloat},
	'mat4x3'              : {'shape': (4, 3) , 'function': glUniformMatrix4x3fv, 'constant': GL_FLOAT_MAT4x3,           'dtype': GLfloat},
	'dmat2'               : {'shape': (2, 2) , 'function': glUniformMatrix2dv  , 'constant': GL_DOUBLE_MAT2,            'dtype': GLdouble},
	'dmat3'               : {'shape': (3, 3) , 'function': glUniformMatrix3dv  , 'constant': GL_DOUBLE_MAT3,            'dtype': GLdouble},
	'dmat4'               : {'shape': (4, 4) , 'function': glUniformMatrix4dv  , 'constant': GL_DOUBLE_MAT4,            'dtype': GLdouble},
	'dmat2x3'             : {'shape': (2, 3) , 'function': glUniformMatrix2x3dv, 'constant': GL_DOUBLE_MAT2x3,          'dtype': GLdouble},
	'dmat2x4'             : {'shape': (2, 4) , 'function': glUniformMatrix2x4dv, 'constant': GL_DOUBLE_MAT2x4,          'dtype': GLdouble},
	'dmat3x2'             : {'shape': (3, 2) , 'function': glUniformMatrix3x2dv, 'constant': GL_DOUBLE_MAT3x2,          'dtype': GLdouble},
	'dmat3x4'             : {'shape': (3, 4) , 'function': glUniformMatrix3x4dv, 'constant': GL_DOUBLE_MAT3x4,          'dtype': GLdouble},
	'dmat4x2'             : {'shape': (4, 2) , 'function': glUniformMatrix4x2dv, 'constant': GL_DOUBLE_MAT4x2,          'dtype': GLdouble},
	'dmat4x3'             : {'shape': (4, 3) , 'function': glUniformMatrix4x3dv, 'constant': GL_DOUBLE_MAT4x3,          'dtype': GLdouble},
	'sampler1D'           : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_1D,             'dtype': GLuint},
	'sampler2D'           : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D,             'dtype': GLuint},
	'sampler3D'           : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_3D,             'dtype': GLuint},
	'samplerCube'         : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_CUBE,           'dtype': GLuint},
	'sampler1DShadow'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_1D_SHADOW,      'dtype': GLuint},
	'sampler2DShadow'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_SHADOW,      'dtype': GLuint},
	'sampler1DArray'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_1D_ARRAY,       'dtype': GLuint},
	'sampler2DArray'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_ARRAY,       'dtype': GLuint},
	'sampler1DArrayShadow': {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_1D_ARRAY_SHADOW, 'dtype': GLuint},
	'sampler2DArrayShadow': {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_ARRAY_SHADOW, 'dtype': GLuint},
	'sampler2DMS'         : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_MULTISAMPLE, 'dtype': GLuint},
	'sampler2DMSArray'    : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'samplerCubeShadow'   : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_CUBE_SHADOW,    'dtype': GLuint},
	'samplerBuffer'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_BUFFER,         'dtype': GLuint},
	'sampler2DRect'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_RECT,        'dtype': GLuint},
	'sampler2DRectShadow' : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_SAMPLER_2D_RECT_SHADOW, 'dtype': GLuint},
	'isampler1D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_1D,         'dtype': GLuint},
	'isampler2D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_2D,         'dtype': GLuint},
	'isampler3D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_3D,         'dtype': GLuint},
	'isamplerCube'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_CUBE,       'dtype': GLuint},
	'isampler1DArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_1D_ARRAY,   'dtype': GLuint},
	'isampler2DArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_2D_ARRAY,   'dtype': GLuint},
	'isampler2DMS'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_2D_MULTISAMPLE, 'dtype': GLuint},
	'isampler2DMSArray'   : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'isamplerBuffer'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_BUFFER, 'dtype': GLuint},
	'isampler2DRect'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_SAMPLER_2D_RECT, 'dtype': GLuint},
	'usampler1D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_1D, 'dtype': GLuint},
	'usampler2D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_2D, 'dtype': GLuint},
	'usampler3D'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_3D, 'dtype': GLuint},
	'usamplerCube'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_CUBE, 'dtype': GLuint},
  # 'usampler2DArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_1D_ARRAY, 'dtype': GLuint},
	'usampler2DArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_2D_ARRAY, 'dtype': GLuint},
	'usampler2DMS'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE, 'dtype': GLuint},
	'usampler2DMSArray'   : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'usamplerBuffer'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_BUFFER, 'dtype': GLuint},
	'usampler2DRect'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_SAMPLER_2D_RECT, 'dtype': GLuint},
	'image1D'             : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_1D, 'dtype': GLuint},
	'image2D'             : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_2D, 'dtype': GLuint},
	'image3D'             : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_3D, 'dtype': GLuint},
	'image2DRect'         : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_2D_RECT, 'dtype': GLuint},
	'imageCube'           : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_CUBE, 'dtype': GLuint},
	'imageBuffer'         : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_BUFFER, 'dtype': GLuint},
	'image1DArray'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_1D_ARRAY, 'dtype': GLuint},
	'image2DArray'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_2D_ARRAY, 'dtype': GLuint},
	'image2DMS'           : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_2D_MULTISAMPLE, 'dtype': GLuint},
	'image2DMSArray'      : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_IMAGE_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'iimage1D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_1D, 'dtype': GLuint},
	'iimage2D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_2D, 'dtype': GLuint},
	'iimage3D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_3D, 'dtype': GLuint},
	'iimage2DRect'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_2D_RECT, 'dtype': GLuint},
	'iimageCube'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_CUBE, 'dtype': GLuint},
	'iimageBuffer'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_BUFFER, 'dtype': GLuint},
	'iimage1DArray'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_1D_ARRAY, 'dtype': GLuint},
	'iimage2DArray'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_2D_ARRAY, 'dtype': GLuint},
	'iimage2DMS'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_2D_MULTISAMPLE, 'dtype': GLuint},
	'iimage2DMSArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'uimage1D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_1D, 'dtype': GLuint},
	'uimage2D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_2D, 'dtype': GLuint},
	'uimage3D'            : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_3D, 'dtype': GLuint},
	'uimage2DRect'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_2D_RECT, 'dtype': GLuint},
	'uimageCube'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_CUBE, 'dtype': GLuint},
	'uimageBuffer'        : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_BUFFER, 'dtype': GLuint},
	'uimage1DArray'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_1D_ARRAY, 'dtype': GLuint},
	'uimage2DArray'       : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_2D_ARRAY, 'dtype': GLuint},
	'uimage2DMS'          : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE, 'dtype': GLuint},
	'uimage2DMSArray'     : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY, 'dtype': GLuint},
	'atomic_uint'         : {'shape': (1, )  , 'function': glUniform1ui        , 'constant': GL_UNSIGNED_INT_ATOMIC_COUNTER, 'dtype': GLuint}
}

temp = {
GL_FLOAT: 'float',
GL_FLOAT_VEC2: 'vec2',
GL_FLOAT_VEC3: 'vec3',
GL_FLOAT_VEC4: 'vec4',
GL_DOUBLE: 'double',
GL_DOUBLE_VEC2: 'dvec2',
GL_DOUBLE_VEC3: 'dvec3',
GL_DOUBLE_VEC4: 'dvec4',
GL_INT: 'int',
GL_INT_VEC2: 'ivec2',
GL_INT_VEC3: 'ivec3',
GL_INT_VEC4: 'ivec4',
GL_UNSIGNED_INT: 'unsigned int',
GL_UNSIGNED_INT_VEC2: 'uvec2',
GL_UNSIGNED_INT_VEC3: 'uvec3',
GL_UNSIGNED_INT_VEC4: 'uvec4',
GL_BOOL: 'bool',
GL_BOOL_VEC2: 'bvec2',
GL_BOOL_VEC3: 'bvec3',
GL_BOOL_VEC4: 'bvec4',
GL_FLOAT_MAT2: 'mat2',
GL_FLOAT_MAT3: 'mat3',
GL_FLOAT_MAT4: 'mat4',
GL_FLOAT_MAT2x3: 'mat2x3',
GL_FLOAT_MAT2x4: 'mat2x4',
GL_FLOAT_MAT3x2: 'mat3x2',
GL_FLOAT_MAT3x4: 'mat3x4',
GL_FLOAT_MAT4x2: 'mat4x2',
GL_FLOAT_MAT4x3: 'mat4x3',
GL_SAMPLER_2D: 'sampler2D',
}


class Uniform:

	def __init__(self, name, location, dtype):
		pass