from pyglet.gl import *

"""
There are 3 types of glUniform functions:
    1. glUniformX        : location, *args
    2. glUniformXv       : location, count, *args
    3. glUniformMatrixXv : location, count, transpose, *args
"""

uniform_function = {
    GL_FLOAT: glUniform1f,
    GL_FLOAT_VEC2: glUniform2f,
    GL_FLOAT_VEC3: glUniform3f,
    GL_FLOAT_VEC4: glUniform4f,
    GL_DOUBLE: glUniform1d,
    GL_DOUBLE_VEC2: glUniform2d,
    GL_DOUBLE_VEC3: glUniform3d,
    GL_DOUBLE_VEC4: glUniform4d,
    GL_INT: glUniform1i,
    GL_INT_VEC2: glUniform2i,
    GL_INT_VEC3: glUniform3i,
    GL_INT_VEC4: glUniform4i,
    GL_UNSIGNED_INT: glUniform1ui,
    GL_UNSIGNED_INT_VEC2: glUniform2ui,
    GL_UNSIGNED_INT_VEC3: glUniform3ui,
    GL_UNSIGNED_INT_VEC4: glUniform4ui,
    GL_BOOL: glUniform1ui,
    GL_BOOL_VEC2: glUniform2ui,
    GL_BOOL_VEC3: glUniform3ui,
    GL_BOOL_VEC4: glUniform4ui,
    GL_FLOAT_MAT2: (glUniformMatrix2fv, 1, GL_TRUE),
    GL_FLOAT_MAT3: (glUniformMatrix3fv, 1, GL_TRUE),
    GL_FLOAT_MAT4: (glUniformMatrix4fv, 1, GL_TRUE),
    GL_FLOAT_MAT2x3: (glUniformMatrix2x3fv, 1, GL_TRUE),
    GL_FLOAT_MAT2x4: (glUniformMatrix2x4fv, 1, GL_TRUE),
    GL_FLOAT_MAT3x2: (glUniformMatrix3x2fv, 1, GL_TRUE),
    GL_FLOAT_MAT3x4: (glUniformMatrix3x4fv, 1, GL_TRUE),
    GL_FLOAT_MAT4x2: (glUniformMatrix4x2fv, 1, GL_TRUE),
    GL_FLOAT_MAT4x3: (glUniformMatrix4x3fv, 1, GL_TRUE),
    # GL_DOUBLE_MAT2: glUniformMatrix2fv,
    # GL_DOUBLE_MAT3: glUniformMatrix3fv,
    # GL_DOUBLE_MAT4: glUniformMatrix4fv,
    # GL_DOUBLE_MAT2x3: glUniformMatrix2x3fv,
    # GL_DOUBLE_MAT2x4: glUniformMatrix2x4fv,
    # GL_DOUBLE_MAT3x2: glUniformMatrix3x2fv,
    # GL_DOUBLE_MAT3x4: glUniformMatrix3x4fv,
    # GL_DOUBLE_MAT4x2: glUniformMatrix4x2fv,
    # GL_DOUBLE_MAT4x3: glUniformMatrix4x3fv,
    GL_SAMPLER_1D: (glUniform1ui, 1, GL_TRUE),
    GL_SAMPLER_2D: (glUniform1ui, 1, GL_TRUE),
    GL_SAMPLER_3D: (glUniform1ui, 1, GL_TRUE),
    # GL_SAMPLER_CUBE: glUniform,
    # GL_SAMPLER_1D_SHADOW: None,
    # GL_SAMPLER_2D_SHADOW: None,
    # GL_SAMPLER_1D_ARRAY: None,
    # GL_SAMPLER_2D_ARRAY: None,
    # GL_SAMPLER_1D_ARRAY_SHADOW: None,
    # GL_SAMPLER_2D_ARRAY_SHADOW: None,
    # GL_SAMPLER_2D_MULTISAMPLE: None,
    # GL_SAMPLER_2D_MULTISAMPLE_ARRAY: None,
    # GL_SAMPLER_CUBE_SHADOW: None,
    # GL_SAMPLER_BUFFER: None,
    # GL_SAMPLER_2D_RECT: None,
    # GL_SAMPLER_2D_RECT_SHADOW: None,
    # GL_INT_SAMPLER_1D: None,
    # GL_INT_SAMPLER_2D: None,
    # GL_INT_SAMPLER_3D: None,
    # GL_INT_SAMPLER_CUBE: None,
    # GL_INT_SAMPLER_1D_ARRAY: None,
    # GL_INT_SAMPLER_2D_ARRAY: None,
    # GL_INT_SAMPLER_2D_MULTISAMPLE: None,
    # GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY: None,
    # GL_INT_SAMPLER_BUFFER: None,
    # GL_INT_SAMPLER_2D_RECT: None,
    # GL_UNSIGNED_INT_SAMPLER_1D: None,
    # GL_UNSIGNED_INT_SAMPLER_2D: None,
    # GL_UNSIGNED_INT_SAMPLER_3D: None,
    # GL_UNSIGNED_INT_SAMPLER_CUBE: None,
    # GL_UNSIGNED_INT_SAMPLER_1D_ARRAY: None,
    # GL_UNSIGNED_INT_SAMPLER_2D_ARRAY: None,
    # GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE: None,
    # GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY: None,
    # GL_UNSIGNED_INT_SAMPLER_BUFFER: None,
    # GL_UNSIGNED_INT_SAMPLER_2D_RECT: None,
    # GL_IMAGE_1D: None,
    # GL_IMAGE_2D: None,
    # GL_IMAGE_3D: None,
    # GL_IMAGE_2D_RECT: None,
    # GL_IMAGE_CUBE: None,
    # GL_IMAGE_BUFFER: None,
    # GL_IMAGE_1D_ARRAY: None,
    # GL_IMAGE_2D_ARRAY: None,
    # GL_IMAGE_2D_MULTISAMPLE: None,
    # GL_IMAGE_2D_MULTISAMPLE_ARRAY: None,
    # GL_INT_IMAGE_1D: None,
    # GL_INT_IMAGE_2D: None,
    # GL_INT_IMAGE_3D: None,
    # GL_INT_IMAGE_2D_RECT: None,
    # GL_INT_IMAGE_CUBE: None,
    # GL_INT_IMAGE_BUFFER: None,
    # GL_INT_IMAGE_1D_ARRAY: None,
    # GL_INT_IMAGE_2D_ARRAY: None,
    # GL_INT_IMAGE_2D_MULTISAMPLE: None,
    # GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY: None,
    # GL_UNSIGNED_INT_IMAGE_1D: None,
    # GL_UNSIGNED_INT_IMAGE_2D: None,
    # GL_UNSIGNED_INT_IMAGE_3D: None,
    # GL_UNSIGNED_INT_IMAGE_2D_RECT: None,
    # GL_UNSIGNED_INT_IMAGE_CUBE: None,
    # GL_UNSIGNED_INT_IMAGE_BUFFER: None,
    # GL_UNSIGNED_INT_IMAGE_1D_ARRAY: None,
    # GL_UNSIGNED_INT_IMAGE_2D_ARRAY: None,
    # GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE: None,
    # GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY: None,
    # GL_UNSIGNED_INT_ATOMIC_COUNTER: None
}